### ISSUE TITLE
Script to generate config for export xls

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#113]
We need a script to generate the initial config for the xls export reading form the XLS shema definition.

**Comment by mattiagiupponi** [comment]
Notes: 
- sheet -> foglio netsic
- fields -> table_name.field_name
- alias -> field_name
- columns -> id netsic
- sheet should be lowercase with only the first lettere capitalized
- table_name and table_alias in lowercase
- use the validator for validate the output schema
