### ISSUE TITLE
Check export configuration and write documentation about it

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#141]
Check the configuration file for the export and write eventually notes in the [Google document](https://docs.google.com/document/d/10eHGJzGAexsfpcZaeAZoLqT40Eo7YQLIy-Rx6wAAfH0/edit?usp=sharing).

Required information are:
- Sheet Name
- Field Name
- Notes
for the XLS definition and also for the XLS validation

**Comment by mattiagiupponi** [comment]
- [x]  The export phase, as discussed, will contain the configuration that was not possible to configure.
- [ ] The validation phase will contain the, will contain the configuration that was not possible to configure.
