### ISSUE TITLE
Create User Manual

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#142]
Create [documentation](https://docs.google.com/document/d/1zCjdGEUcsN7YbOX2xHeChs9_N7ratRkkEVvhbzPnEvE/edit?usp=sharing)about usage of the application and how to configure export (XLS, SHP) using the JSON file.

**Comment by mattiagiupponi** [comment]
@chpicone The documentation is completed and ready for a review.
