### ISSUE TITLE
Permission denied to write in the FTP folder

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#187]
When we try to export data the process terminates with the following error:

> Permission denied: '/srv/ftp/export/task_30.zip'

It seems we dont have permission to write/copy file into the /srv/ftp/export folder.

@lpasquali do you think our problem or we have to ask the customer to check these permissions?

**Comment by lpasquali** [comment]
Fixed permissions on export and import directories "dbiait" is in group "ftp" but "/srv/ftp/export" was with umask 0750 so I changed that to 0770, everything worked out then.

**Comment by chpicone** [comment]
It works, thx @lpasquali
