### ISSUE TITLE
Check error in the export

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#188]
Customer start writing some anomalies [here](https://docs.google.com/spreadsheets/d/1BT0mlOqiLs_UnGWpwi0xvNFeI5iGikqliicfveG08w8/edit#gid=0)

**Comment by chpicone** [comment]
[Here](https://drive.google.com/drive/folders/1UEiTz9M-LoOj12YjIXyLZegz3I5Yfdr6?usp=sharing) the folder with the requirement

**Comment by mattiagiupponi** [comment]
Following a short recap of the activities
|Status| Name |     function      | Todo |
|---|:----------|:-------------:|------:|
|| Tronchi fognatura |  populate_fognat_tronchi | field `depurazione` check how is calculated and check with AIT data |
|| Tronchi - Collettori |    populate_collett_tronchi|   1) n of records not match between db & extraction in excel 2) check filed `depurazione`|
|| Shape Fognatura (FGN_SHAPE) | populate_fgn_shape |   field `recapito` always empty | 
||Lunghezza rete fognatura|populate_lung_rete_fgn | check field `tipo_infr` does not match the specifications 2) check sum of length of rome `reti` does not match sum of `condotte` |
||Allacci - Fognatura|determine_fgn_allacci|table `fgn_allaccio` always empty, check on join with `utenza_sap`|

Shapefile:
|status| Shapefile name |     Todo     |
|---|:----------|:-------------:|
||pozzi|round at 6° decimal number|


XLS:
|Status| transformation/validation |     Todo     |
|---|:----------|:-------------:|
|||transformation|If the key during `domain` lookup is not found, the cell must be empty and the log silenced|
