### ISSUE TITLE
Prepare PROD environment

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#195]
To prepare the PROD environment it is necessary:
- [x] run Jenkins JOB to install the Django Web App
- [x] run Jenkins JOB to install the DB tables
- [x] run Jenkins JOB to install the PlPgSQL functions
- [x] check if the WebApp is up&runnig 
- [x] check login using LDAP
- [x] check if the FTP folder is readable/writable

**Comment by chpicone** [comment]
@randomorder I think it is a simple task.
@lpasquali can you confirm it?

**Comment by lpasquali** [comment]
@chpicone yes it should be fast

**Comment by lpasquali** [comment]
@chpicone I tried to import the test package
but it keeps being in queue and I see no progress in its job

**Comment by lpasquali** [comment]
production application looks like to work correctly as in test

**Comment by chpicone** [comment]
thx @lpasquali
