### ISSUE TITLE
Archivio Pompe

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#201]
> La tabella archivio pompe sul db contiene 2640 record ma l'export in xls nei fogli rispettivi non produce niente.
> l'esportazione è la numero 47. sul file xls.json non ci sono filtri quindi dovrebbe esportare tutto.

**Comment by chpicone** [comment]
- POZZI_POMPE (tipo_oggetto='ACQ_CAPTAZIONE')
- POTAB_POMPE (tipo_oggetto='ACQ_POTABILIZ')
- POMPAGGI_POMPE (tipo_oggetto=’ACQ_POMPAGGIO’) 
- SOLLEV_POMPE (tipo_oggetto='FGN_IMP_SOLLEV')
- DEPURATO_POMPE (tipo_oggetto='FGN_TRATTAMENTO')

**Comment by mattiagiupponi** [comment]
Configuration files are fixed and tested on local environment. The related sheets are now correclty populated
