### ISSUE TITLE
Missing Unique Identifier on table A_FGN_REL_PROD_IMM

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#202]
> 1) se non sbaglio  manca la chiave primaria alla tabella A_FGN_REL_PROD_IMM :
> -- Table: dbiait_analysis.a_fgn_rel_prod_imm
> 
> -- DROP TABLE dbiait_analysis.a_fgn_rel_prod_imm;
> 
> CREATE TABLE dbiait_analysis.a_fgn_rel_prod_imm
> (
>     id_produttivo character varying(32) COLLATE pg_catalog."default",
>     id_immissione character varying(32) COLLATE pg_catalog."default",
>     id_sist_fogn character varying(32) COLLATE pg_catalog."default"
> )
> WITH (
>     OIDS = FALSE
> )
> TABLESPACE pg_default;
> 
> ALTER TABLE dbiait_analysis.a_fgn_rel_prod_imm
>     OWNER to dbiait_test;
> 
> GRANT ALL ON TABLE dbiait_analysis.a_fgn_rel_prod_imm TO dbiait_test;
> 
> GRANT SELECT, DELETE, UPDATE, INSERT ON TABLE dbiait_analysis.a_fgn_rel_prod_imm TO devitis;
> 
> GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE dbiait_analysis.a_fgn_rel_prod_imm TO diciommo;
> 
> GRANT INSERT, DELETE, UPDATE, SELECT ON TABLE dbiait_analysis.a_fgn_rel_prod_imm TO favilli;
> 
> 2)  Rimane in sospeso il modello dati delle località.

**Comment by mattiagiupponi** [comment]
The table `A_FGN_REL_PROD_IMM` is totally different from the table `FGN_REL_PROD_IMM`.
By looking at the table, some duplicate values are available, so is not possible at the moment to define a primary key.
Is needed to ask to the client which one is the expected primary key and then fix the procedure that creates the table in order to remove the duplicates

**Comment by chpicone** [comment]
I discussed with the customer.
They confirm that the table FGN_REL_PROD_IMM is different because they have a table inside the GeoPackage (so we have to remove it from the SQL install script).
The PK in the table A_FGN_REL_PROD_IMM is on the fields: id_produttivo, id_immissione.

**Comment by chpicone** [comment]
Unfortunately this table contains duplicated records so at the moment we cannot add the PK definition.
I wrote an email to the customer if we can remove the duplicated items or if they prefer to adjust the table manually before to apply the PK definition

**Comment by chpicone** [comment]
```
DELETE FROM dbiait_analysis.a_fgn_rel_prod_imm where id_produttivo in ('PAFPRO00000000012890','PAFPRO00000000012803','PAFPRO00000000013150');
ALTER TABLE dbiait_analysis.a_fgn_rel_prod_imm ADD CONSTRAINT a_fgn_rel_prod_imm_pk PRIMARY KEY (id_produttivo,id_immissione);
INSERT INTO dbiait_analysis.a_fgn_rel_prod_imm(id_produttivo, id_immissione) VALUES('PAFPRO00000000012890','PAPIMM00000000006069');
INSERT INTO dbiait_analysis.a_fgn_rel_prod_imm(id_produttivo, id_immissione) VALUES('PAFPRO00000000012803','PAPIMM00000000006205');
INSERT INTO dbiait_analysis.a_fgn_rel_prod_imm(id_produttivo, id_immissione) VALUES('PAFPRO00000000013150','PAPIMM00000000006168');
```

**Comment by chpicone** [comment]
OK, we can remove the duplicated rows. We will do this task when we will release the new version.
