### ISSUE TITLE
DBIAIT - Update documentation

### ISSUE THREAD

**Issue by mattiagiupponi** [geosolutions-it/C179-DBIAIT#214]
Update client "user manual" in order to add information about:
- Trasformazioni in elaborazione (IF, round, ecc..)
- Trasformazioni in query (TO_BIT, from_float_to_int)

[File location](https://docs.google.com/document/d/1zCjdGEUcsN7YbOX2xHeChs9_N7ratRkkEVvhbzPnEvE)

**Comment by chpicone** [comment]
Add documentation for the new trasformation named DECODE_COM
