### ISSUE TITLE
Punti di clorazione su rete e adduzione

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#220]
[Ref. Chapter 4 - Punti di clorazione su rete e adduzione](https://drive.google.com/file/d/1Rtcfhso5aH7PY5EX8r2cLRFWpP2_xas9/view?usp=sharing)
In the export of sheet DISTRIBUZIONI and ADDUTTRICI (see the new [definition of the export](https://drive.google.com/file/d/1-yCXTqfbBcXRMvELwNnO9RDj3Ub-aZNf/view?usp=sharing)), we have to report the number of "clorazione" nodes.
The database contains a layer named ACQ_CLORATORE containing junctions' nodes between water networks (condotte).
A new procedure will associate to each nodes of acq_cloratore layers the code of a edge of condotta (id_rete).
A stats table will contain for each edge of condotta (id_rete) the number of associated cloratore nodes.

**Comment by mattiagiupponi** [comment]
The new procedure is maded and the `stats_clorazione` is done.
I also implement an example of unittest for this procedure in order to approach the procedure in postgres with a TDD approach.
Please validate the spatial join and review the test before merge the PR
