### ISSUE TITLE
Lunghezza rete ispezionata

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#225]
[Ref. Chapter 6 -Lunghezza rete ispezionata](https://drive.google.com/file/d/1Rtcfhso5aH7PY5EX8r2cLRFWpP2_xas9/view?usp=sharing)
- Create a static table named TAB_ISPEZIONI
- Adapt procedure to calculate FGN_LUNGHEZZA_RETE to store 2 additional fields (lung_rete_mista, lung_rete_nera)
- Adapt configuration of sheet FOGNATURA to report the sum of these types of lengths

**Comment by mattiagiupponi** [comment]
- [x] Create a static table named TAB_ISPEZIONI
- [ ] Adapt procedure to calculate FGN_LUNGHEZZA_RETE to store 2 additional fields (lung_rete_mista, lung_rete_nera)
- [ ] Adapt configuration of sheet FOGNATURA to report the sum of these types of lengths

**Comment by mattiagiupponi** [comment]
Before deploy the new feature is needed to add `tab_ispezioni` table , update the table `fgn_lunghezza_rete`
