### ISSUE TITLE
cast attribute for the column definition in the export config

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#242]
We need to add an optional attribute **cast** with the possibility to set postgres data types (eg. BIT, INTEGER, VARCHAR, etc) to make PyPika able to compose query like that:

> select mytable.myfield::INTEGER from mytable

> "sources": [
>         {
>             "fields": [
>                 {"name": "mytable.myfield", "alias": "myfield", "cast": "INTEGER"},

**Comment by mattiagiupponi** [comment]
Attribute `CAST` is now available to be added to the configuration files (both `shape` and `xls`)
The new attribute needs to be defined in this way: 
```json
{"name": "acq_shape.id_conserv", "alias": "id_conserv", "cast": "INTEGER"}
```
The json will be converted in:
```json
CAST("acq_shape"."id_conserv" AS INTEGER) "id_conserv"
```
Or for `VARCHARS` if is needed to specify also the length, needs to be defined in this way:
```json
{"name": "acq_shape.id_conserv", "alias": "id_conserv", "cast": "VARCHAR(255)"}
```
The json will be converted in:
```json
CAST("acq_shape"."id_conserv" AS VARCHAR(255)) "id_conserv"
```

Cast and functions could be used both during the `JSON` definition for example:
```json
{"name": "acq_shape.id_conserv", "alias": "id_conserv", "functon": "TO_BIT", "cast": "INTEGER"}
```
The JSON will be converted in:
```json
CAST(TO_BIT("id_conserv") AS INTEGER)
```
