### ISSUE TITLE
Grant permission on schema to specific role

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#249]
We need to add statements to grant permission to specific roles after the execution of the following tasks:

- **import** (of geopakackage): 
> GRANT SELECT ON ALL TABLES IN SCHEMA dbiait_analysis TO DBIAIT_ANL_ROLE_R;

- **freeze**:
> GRANT SELECT ON ALL TABLES IN SCHEMA dbiait_freeze TO DBIAIT_FRZ_ROLE_R;
> GRANT SELECT, UPDATE, INSERT, DELETE ON ALL TABLES IN SCHEMA dbiait_freeze TO DBIAIT_FRZ_ROLE_W;
> GRANT ADMINISTRATOR ON ALL TABLES IN SCHEMA dbiait_freeze TO DBIAIT_FRZ_ROLE_D;

**Comment by mattiagiupponi** [comment]
- [ ]  import (of geopakackage)
- [ ] freeze
