### ISSUE TITLE
Freeze: error copying sql script

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#261]
The freeze process fails with this errror:
![image.png](https://images.zenhubusercontent.com/5e98219c18069195a59f5217/930bb5fe-3874-498c-872b-f2cef8b1232b)

The task is trying to read the files from the incorrect folder (ftp)... we have to copy them from the source data folder.

**Comment by mattiagiupponi** [comment]
Fix done and the PR is [open](https://github.com/geosolutions-it/C179-DBIAIT/pull/262)
