### ISSUE TITLE
Database tuning

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#288]
We need to check the database configuration to make it performing well to run procedures.
At the moment I found a problem with work_mem too low (4MB). I think better to increase this value to 256MB, for their purposes.
We need to put also this information in the documentation.

**Comment by randomorder** [comment]
@lpasquali please check postgresql config and propose a new one, tuned for the environment. Then we're going to schedule  the operation with the client

**Comment by chpicone** [comment]
As suggested by @randomorder we can try to use pgtune to obtain an initial configuration and then have a quick discussion on these parameters

**Comment by chpicone** [comment]
At the moment to make them able to continue with their tests (and give us the OK to move on production) we set at runtime this option when they execute the procedure:
> SET work_mem = '256MB';

**Comment by lpasquali** [comment]
I will generate a config with pgtune and post it here for further discussion,taking into account hw config of running cluster @randomorder @chpicone

**Comment by lpasquali** [comment]
if they have HDD

```
# DB Version: 10
# OS Type: linux
# DB Type: web
# Total Memory (RAM): 16 GB
# CPUs num: 8
# Connections num: 100
# Data Storage: hdd

max_connections = 100
shared_buffers = 4GB
effective_cache_size = 12GB
maintenance_work_mem = 1GB
checkpoint_completion_target = 0.7
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 4
effective_io_concurrency = 2
work_mem = 10485kB
min_wal_size = 1GB
max_wal_size = 4GB
max_worker_processes = 8
max_parallel_workers_per_gather = 4
max_parallel_workers = 8
```
if they have SSD
```
# DB Version: 10
# OS Type: linux
# DB Type: web
# Total Memory (RAM): 16 GB
# CPUs num: 8
# Connections num: 100
# Data Storage: ssd

max_connections = 100
shared_buffers = 4GB
effective_cache_size = 12GB
maintenance_work_mem = 1GB
checkpoint_completion_target = 0.7
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 10485kB
min_wal_size = 1GB
max_wal_size = 4GB
max_worker_processes = 8
max_parallel_workers_per_gather = 4
max_parallel_workers = 8
```

**Comment by lpasquali** [comment]
@chpicone I think that raising 10Mb to 256Mb for work_mem is quite doable given resources, let's hear what type of disk they have and I'll give you the final proposal

**Comment by lpasquali** [comment]
@randomorder concerning connections, I put 100 as I found, should this number re-thought because of the new DBIAIT app?

**Comment by chpicone** [comment]
@lpasquali DBIAIT app will used by few people (generally 2 or 3) and for a specific moment (probably just 1 week per year).
Just few tasks can run concurrently and to complete the whole process it is necessary less than 10 minutes.
So I think we dont have to pay attention to the number of user connections (they are also the same using the WebGIS).
It was necessary to increase the size of work_mem just to make the task able to finish.

**Comment by lpasquali** [comment]
they have something a little better than SSD, which is FMD (see this Hitachi whitepaper on the disks their storage mounts): https://www.hitachivantara.com/en-us/pdfd/white-paper/accelerated-flash-whitepaper.pdf
so final proposal would be:
```
# DB Version: 10
# OS Type: linux
# DB Type: web
# Total Memory (RAM): 16 GB
# CPUs num: 8
# Connections num: 100
# Data Storage: ssd

max_connections = 100
shared_buffers = 4GB
effective_cache_size = 12GB
maintenance_work_mem = 1GB
checkpoint_completion_target = 0.7
wal_buffers = 16MB
default_statistics_target = 100
random_page_cost = 1.1
effective_io_concurrency = 200
work_mem = 10485kB
min_wal_size = 1GB
max_wal_size = 4GB
max_worker_processes = 8
max_parallel_workers_per_gather = 4
max_parallel_workers = 8
```
and for such heavier jobs @chpicone will keep the `work_mem` overridden in SQL code. 
what do you think @chpicone and @randomorder ?

**Comment by chpicone** [comment]
I think it could be a correct configuration.
All procedure was able to run also with work_mem to 4MB, so I think 10MB it is enough.
Anyway just for some important process (1 thread) I will continue using custom settings at runtime.

**Comment by randomorder** [comment]
> they have something a little better than SSD, which is FMD (see this Hitachi whitepaper on the disks their storage mounts): https://www.hitachivantara.com/en-us/pdfd/white-paper/accelerated-flash-whitepaper.pdf
> so final proposal would be:
> 
> ```
> # DB Version: 10
> # OS Type: linux
> # DB Type: web
> # Total Memory (RAM): 16 GB
> # CPUs num: 8
> # Connections num: 100
> # Data Storage: ssd
> 
> max_connections = 100
> shared_buffers = 4GB
> effective_cache_size = 12GB
> maintenance_work_mem = 1GB
> checkpoint_completion_target = 0.7
> wal_buffers = 16MB
> default_statistics_target = 100
> random_page_cost = 1.1
> effective_io_concurrency = 200
> work_mem = 10485kB
> min_wal_size = 1GB
> max_wal_size = 4GB
> max_worker_processes = 8
> max_parallel_workers_per_gather = 4
> max_parallel_workers = 8
> ```
> 
> and for such heavier jobs @chpicone will keep the `work_mem` overridden in SQL code.
> what do you think @chpicone and @randomorder ?

Sounds Good
Please schedule the operation with PA and add a PostgreSQL section to our Wiki with a subsection about postgresql conf tuning @lpasquali

**Comment by lpasquali** [comment]
@randomorder https://github.com/geosolutions-it/DevOps/wiki/Postgres-database-tuning

**Comment by chpicone** [comment]
@randomorder I sent an email to PA asking to update the configuration of the Postgres database in their environment on tuesday after 5PM. Still waiting...

**Comment by randomorder** [comment]
> @randomorder https://github.com/geosolutions-it/DevOps/wiki/Postgres-database-tuning

I've made some minor changes to the page @lpasquali
Please move it under a PostgreSQL global page and add a TOC if possible

**Comment by lpasquali** [comment]
@randomorder @chpicone restart of postgres with new config values has been done

**Comment by randomorder** [comment]
pelase close the issue when happy @chpicone
