### ISSUE TITLE
Install PgRouting extension

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#29]
For the phase 3 we need to have PgRouting extension installed on the PA's PostgreSql database.

**Comment by randomorder** [comment]
I had a look at the system. Currently the pgrouting extension is not installed. There is no pgrouting available from the same repo that we used to install postgresql. There are two options:
1 - Build the the extension
2 - Install it from another repo

Building should be pretty straigtforward. I looked at the sources and there are very few dependencies 
```

Building requirements
--------------------
* Perl
* C and C++ compilers
  * GNU >= 4.8
  * MSVC >= 18.0
* Postgresql >= 9.4
* The Boost Graph Library (BGL) >= 1.53
* CMake >= 3.2
* Sphinx >= 1.8
```

I suggest we try using the version from the alternative repo (`zypper install postgresql10-pgRouting`) and if it doesn't work we build it from source. 

Remember to port this to the Ansible playbook, if possible

**Comment by randomorder** [comment]
Is this the activity we did together @chpicone ? I'm not 100% sure

**Comment by chpicone** [comment]
We have to install it. But we can do later or when we will create dbiait databases (test and prod).

**Comment by chpicone** [comment]
I put this issue in blocked state.
May be we can work on networks directly with PyQGIS or NetworkX python libraries (so without install pgRouting).
For the creation of the network I used directly PostGIS.
