### ISSUE TITLE
Check LDAP configuration

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#299]
this is the email received by the customer:

> Buongiorno a tutti,
> durante i nostri controlli di pre-golive del servizio DBIAIT abbiamo riscontrato, in merito alle configurazioni LDAP, quanto segue:
> 
>     è presente il puntamento soltanto ad un domain controller DC01.publiacqua.it e non ad entrambi (in quanto è presente anche DC02.publiacqua.it);
>     il puntamento avviene tramite LDAP e non LDAPS.
> 
> root@dbi-ait:~# grep -i ldap /etc/uwsgi/apps-enabled/dbiait.ini
> env = LDAP_HOST=ldap://dc01.publiacqua.it:389
> 
> Potrei chiedervi di effettuare un controllo in tal senso prima del GoLive di domani?

@randomorder can someone take a look on this issue?

**Comment by lpasquali** [comment]
> The same for LDAPS:
> https://django-auth-ldap.readthedocs.io/en/latest/authentication.html?highlight=LDAPS

this should work out of the box, I agree that code may need some retouch for server redundancy, which is supported by ldap url schema afaik

**Comment by randomorder** [comment]
there are other activities to carry on for PA. Let's try to "batch" them to be more efficient limit context switches.
@chpicone knows what I am talking about (postgresql stats for instance)

**Comment by randomorder** [comment]
[LDAP configuration documentation](https://docs.google.com/document/d/1HTQ9vxB8p669eWMafDhuk1F1i3B5wjYkhh2MLvvhBGg/edit#) updated
