### ISSUE TITLE
Process locked: still running

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#343]
The customer reported an issue on the PROD environment about the "utenza_servizio" process still running after some hours.

**Comment by chpicone** [comment]
My investigation:

```
SELECT *
FROM pg_stat_activity 
where usename = 'dbiait_prod' and client_addr='10.140.12.67'
```
then check if there are some statements with columns wait_event_type = *Lock*
and wait_event  = *transactionid*

**Comment by chpicone** [comment]
@mattiagiupponi take a look to this screenshot:
![image](https://user-images.githubusercontent.com/2872823/121769319-2f423100-cb63-11eb-9c7e-c546f41a1ef2.png)

**Comment by chpicone** [comment]
I started the first item in the list when all the others were failed.
But after 1 min the 3rd item started running (It is very strange), and I found now that we have 2 process of the same type running:
![image](https://user-images.githubusercontent.com/2872823/121769351-76c8bd00-cb63-11eb-94e6-75acd0a47a99.png)

**Comment by mattiagiupponi** [comment]
@chpicone the only reason why the third process was running again, can be explained here https://dramatiq.io/guide.html#message-retries
We should try to set `dramatiq` to not re-try any kind of message due to errors
