### ISSUE TITLE
Delete table acq_area_poe not anymore needed

### ISSUE THREAD

**Issue by EddyCatt** [geosolutions-it/C179-DBIAIT#353]
Client asked to delete table acq_area_poe not anymore needed and related functions (codice_schema_acq";"denominazione_schema_acq" )

**Comment by mattiagiupponi** [comment]
@EddyCatt in a nutshell those are the main step required to complete this issue:

- Remove `populate_schema_acq` function
- Update all JSON configuration
- Ensure that all JSON configurations are still working
- Fix all unittest (app and DB)
- Update the client dev environment and run all unittest via Jenkins to ensure that everything is still working
- Copy all JSON configuration to the Client FTP
- Perform an export on the development environment
- Execute the Acquedotti function on the development server to evaluate that is still working
