### ISSUE TITLE
new update for DBIAIT export

### ISSUE THREAD

**Issue by mattiagiupponi** [geosolutions-it/C179-DBIAIT#356]
Clients require new changes on the export phase for the following sheets:
- Adduttrici **cap2**
- Adduttrici/Distribuzioni e Fognature/Collettori **cap3**
- Depuratori **cap4**
- Distribuzioni **cap5**
- Distrib_tronchi/Fognat_tronchi **cap6**
- Fiumi/Laghi/Pozzi/Sorgenti **cap7**
- Fognature **cap8**

Attached the PDF with the instruction provided by the client

[20220104 - Integrazioni DBI AIT.pdf](https://github.com/geosolutions-it/C179-DBIAIT/files/7912699/20220104.-.Integrazioni.DBI.AIT.pdf)

cc: @EddyCatt

**Comment by mattiagiupponi** [comment]
@EddyCatt is possible ask the following things to the client?

**Cap2 Adduttrici:**
- field **117690** is not populated by the script, and the field "_volume erogato_" belongs to id **117700**, they mean this one?

**Cap3 Adduttrici/Distribuzioni e Fognature/Collettori:**
- Can the client provide us an example of the new "utenza_sap" table?

**Cap7 Fiumi/Laghi/Pozzi/Sorgenti:**
The table `a_acq_capt_conces` was excluded only in the `Laghi` json configuration file, while in the others is already considered (the extraction will take some value and place them in the column requested in the previous development)
example: 
https://github.com/geosolutions-it/C179-DBIAIT/blob/b66ac4bdd3d6f3e842518459f20c93f23f1a6b64/export/config/current/sheet_configs/config_pozzi.json#L188-L198

**Cap8 Fognature:**
- the field with 60500 id, have the following description: 

> Prevedere il caricamento di un file csv contenente le reti fognarie con stato opera = 6 perché non presenti nel GIS

What this mean? They will provide us a CSV and we need to create the table and the join? They will create the table and we need to change the join to retrieve the value?

**Comment by EddyCatt** [comment]
@mattiagiupponi 
Found issues:

Table Adduttrici
ID 117690
Request: In case of blank value, convert to 0 value
Issue: Table still has blank values 

I have one doubt about the following tables:
   Table Adduttrici: Only 0 and blank values...
   Table distribuzioni: empty
These two tables are the results of the new filter applied on the new field called "M2-M3a exclusion" to be added in the user_sap table, based on which the records with values in this field must be excluded from the calculation....

**Comment by mattiagiupponi** [comment]
> Table Adduttrici ID 117690 Request: In case of blank value, convert to 0 value Issue: Table still has blank values

As written in the last email from the client, the target value was "volume erogato" with the 117700 ID and not the one in the file. The changes were applied to 117700 and not 117690. Can you confirm this?

> I have one doubt about the following tables: Table Adduttrici: Only 0 and blank values... Table distribuzioni: empty These two tables are the results of the new filter applied on the new field called "M2-M3a exclusion" to be added in the user_sap table, based on which the records with values in this field must be excluded from the calculation....

The issue was that the stub data are not updated to the last value available since are meant for testing and they should be immutable. To populate those sheets, I have updated my local stub instance with some extra data.
On drive, is available the updated file for a new review

**Comment by EddyCatt** [comment]
I sent the zip to the client.
Waiting for the review

**Comment by EddyCatt** [comment]
They've asked to deploy in QAS for testing the modifications
