### ISSUE TITLE
Mantainance on the PostGis database

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#49]
In the PostgreSql database server  of PA we need to create:

- [x] database **dbiait_prod**
- [x] database **dbiait_test**
- [x] copy the [provided ntv2 file](https://drive.google.com/file/d/1rQOiAt73i-3LuGHDmQiEbNIBKFn2U8SQ/view?usp=sharing) in the path of **PROJ_LIB** and restart the PG instance.
- [x] try the following SQL statement to verify the result:
> SELECT ST_X(geom), ST_Y(geom) FROM(
> 	SELECT ST_TRANSFORM(
> 		ST_SETSRID(ST_POINT(652833.5003,4864367.865), 25832), 
> 		'+proj=tmerc +lat_0=0 +lon_0=9 +k=0.9996 +x_0=1500000 +y_0=0 +ellps=intl +units=m +nadgrids=gridRM40_ETRS89.gsb'
> 	) geom
> ) t

We expect these values: **1652863.1900 | 4864384.8905**

**Comment by chpicone** [comment]
@randomorder can you confirm this path for the location of the nadgrids file?
/apps/pgsql/data/gridRM40_ETRS89.gsb

**Comment by randomorder** [comment]
yes

**Comment by lpasquali** [comment]
I think here I need to start from debait_test to satisfy #74 @chpicone @randomorder is this correct?

**Comment by randomorder** [comment]
just create both DBs
it should take 1 min

**Comment by lpasquali** [comment]
done
I added two distinct application users for prod and test, started adding information [here](https://docs.google.com/document/d/1ieocK40MCw74aIpB6HusdtNi9vLIi91egFs_b_yXRcc/edit?ts=5fb25a68#)
