### ISSUE TITLE
Implement the base process task

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#60]
We need to implement a python process task to be able to execute a specific stored procedure.
A configuration table (eg named process) contains the foloowing fields:

- **id**: unique identifier of the process
- **name**: name of the process (to show in the process page, in the process list table)
- **algorithm**: nome of the stored procedure to call

When the user asks the scheduler system to add a specific process we have to add the information about the ID and ALGORITHM to use.
The name of the algorithm is the name of the PlPgSql function to call.

These function dont accept parameters and return a boolean (TRUE or FALSE) or can raise an exception.

All the processes function are in the ANALYSIS schema.

We have to make the following steps into the run method of the task:

- change the status from waiting to running
- call the procedure making a SQL query call like: 
> SELECT {analysis schema}.{algorithm}( );
- If an error occurs or the fucntion return FALSE change the status to fails and log the error message
- If the function returns TRUE change the staus to done and progress to 100%

**Comment by chpicone** [comment]
Località Istat -> populate_pop_res_loc

**Comment by chpicone** [comment]
@abulojoshua1, please read the name of the schema from the configuration.
Here it is fixed!:
![image](https://user-images.githubusercontent.com/2872823/97788127-c3ecb580-1bb6-11eb-9e79-a8f4fedc9017.png)

**Comment by chpicone** [comment]
In the configuration we need to define 3 variables, 1 per each schema:
- system => dbiait_system
- analysis => dbiait_analysis
- freeze => dbiait_freeze

**Comment by abulojoshua1** [comment]
> @abulojoshua1, please read the name of the schema from the configuration.
> Here it is fixed!:
> ![image](https://user-images.githubusercontent.com/2872823/97788127-c3ecb580-1bb6-11eb-9e79-a8f4fedc9017.png)

Ok @chpicone, I'll make a fix for this and push new changes.

**Comment by abulojoshua1** [comment]
> **Name of the process -> Name of the PlPgSQL procedure**
> 
> * [ ]  Località Istat -> populate_pop_res_loc
> * [ ]  Percentuale popolazione servita per località -> populate_distrib_loc_serv
> * [ ]  Popolazione residente Istat per comune -> populate_pop_res_comune
> * [ ]  Percentuale popolazione servita sulla rete per comune -> populate_distr_com_serv
> * [ ]  Servizio utenza -> populate_utenza_servizio

@chpicone, what are the corresponding names of the following:
> * [ ]  populate_distrib_tronchi
> * [ ]  populate_addut_tronchi
> * [ ]  populate_fognat_tronchi
> * [ ]  populate_collett_tronchi
> * [ ]  populate_lung_rete_acq
> * [ ]  populate_info_condotte_acq
> * [ ]  populate_lung_rete_fgn
> * [ ]  populate_abitiani_trattati
> * [ ]  populate_lung_rete_acq
> * [ ]  populate_info_condotte_acq
> * [ ]  populate_lung_rete_fgn

**Comment by chpicone** [comment]
@abulojoshua1 
[here ](https://docs.google.com/spreadsheets/d/1BT0mlOqiLs_UnGWpwi0xvNFeI5iGikqliicfveG08w8/edit#gid=0)you can see a list (not definitive) containing the list of procedures. 
But we have to show just the procedures defined (checked) in the column G
