### ISSUE TITLE
Install machine in PA Test environment

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#74]
We need to configure the Test environment for PA:

- [x] QGIS
- [x] Django WebApp
- [x] RabbitMQ
- [x] check shared folder (it is the folder PA will use to put geopackage via FTP)
- [x] check database connectivity
- [x] check LDAP connectivity (may be to ask Neri about configuration of user groups)
- [x] designed virtualhosts for prod and test

**Comment by lpasquali** [comment]
I asked @randomorder because I can't login with usual credentials as I should

**Comment by randomorder** [comment]
access restored

**Comment by lpasquali** [comment]
using master: 
I get this error, I got this error running `python3 manage.py rundramatiq` once on our environment but I never got it with the command in the readme from master branch that is `python3 manage.py global_interpreter_rundramatiq`
```
(dbiait) dbiait@dbi-ait-qas:~/C179-DBIAIT$ env | grep PYTHON
PYTHONPATH=/usr/share/qgis/python/:/usr/share/qgis/python/plugins:/usr/lib/python3/dist-packages/qgis:/usr/share/qgis/python/qgis:/home/dbiait/.local/lib/python3.6/site-packages
(dbiait) dbiait@dbi-ait-qas:~/C179-DBIAIT$ python3 manage.py global_interpreter_rundramatiq
 * Discovered tasks module: 'django_dramatiq.tasks'
 * Discovered tasks module: 'app.scheduler.tasks.base_task'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.config_scraper'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.domains_parser'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.exceptions'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.export_shapefile'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.export_xls'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.transformations'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.validations'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.config_scraper'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.domains_parser'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.exceptions'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.export_shapefile'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.export_xls'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.transformations'
 * Discovered tasks module: 'app.scheduler.tasks.export_definitions.validations'
 * Discovered tasks module: 'app.scheduler.tasks.export_task'
 * Discovered tasks module: 'app.scheduler.tasks.freeze_task'
 * Discovered tasks module: 'app.scheduler.tasks.import_definitions.base_import'
 * Discovered tasks module: 'app.scheduler.tasks.import_definitions.import_csv'
 * Discovered tasks module: 'app.scheduler.tasks.import_definitions.import_gpkg'
 * Discovered tasks module: 'app.scheduler.tasks.import_definitions.base_import'
 * Discovered tasks module: 'app.scheduler.tasks.import_definitions.import_csv'
 * Discovered tasks module: 'app.scheduler.tasks.import_definitions.import_gpkg'
 * Discovered tasks module: 'app.scheduler.tasks.import_task'
 * Discovered tasks module: 'app.scheduler.tasks.process_tasks'
 * Running dramatiq: "dramatiq --path . --processes 4 --threads 4 django_dramatiq.setup django_dramatiq.tasks app.scheduler.tasks.base_task app.scheduler.tasks.export_definitions.config_scraper app.scheduler.tasks.export_definitions.domains_parser app.scheduler.tasks.export_definitions.exceptions app.scheduler.tasks.export_definitions.export_shapefile app.scheduler.tasks.export_definitions.export_xls app.scheduler.tasks.export_definitions.transformations app.scheduler.tasks.export_definitions.validations app.scheduler.tasks.export_definitions.config_scraper app.scheduler.tasks.export_definitions.domains_parser app.scheduler.tasks.export_definitions.exceptions app.scheduler.tasks.export_definitions.export_shapefile app.scheduler.tasks.export_definitions.export_xls app.scheduler.tasks.export_definitions.transformations app.scheduler.tasks.export_definitions.validations app.scheduler.tasks.export_task app.scheduler.tasks.freeze_task app.scheduler.tasks.import_definitions.base_import app.scheduler.tasks.import_definitions.import_csv app.scheduler.tasks.import_definitions.import_gpkg app.scheduler.tasks.import_definitions.base_import app.scheduler.tasks.import_definitions.import_csv app.scheduler.tasks.import_definitions.import_gpkg app.scheduler.tasks.import_task app.scheduler.tasks.process_tasks"

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/dbiait/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/dbiait/.local/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/dbiait/.local/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/dbiait/.local/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/dbiait/.local/lib/python3.6/site-packages/django_dramatiq/management/commands/rundramatiq.py", line 112, in handle
    os.execvp(executable_path, process_args)
  File "/usr/lib/python3.6/os.py", line 559, in execvp
    _execvpe(file, args)
  File "/usr/lib/python3.6/os.py", line 604, in _execvpe
    raise last_exc.with_traceback(tb)
  File "/usr/lib/python3.6/os.py", line 594, in _execvpe
    exec_func(fullname, *argrest)
FileNotFoundError: [Errno 2] No such file or directory
(dbiait) dbiait@dbi-ait-qas:~/C179-DBIAIT$ 
```

**Comment by lpasquali** [comment]
@chpicone @randomorder I also need to configure a proxypass on the two web balancers, is this right?

**Comment by randomorder** [comment]
yup

**Comment by chpicone** [comment]
@lpasquali I will check tomorrow about this error. We are able to run correctly using the master branch in our test environment.

**Comment by randomorder** [comment]
what's the status on this @lpasquali 
I see the estimate was changed 3 hours ago. Does it mean you need 1 more day of work or 1 day in total (including yesterday and this morning work)?

**Comment by chpicone** [comment]
@lpasquali  for the shared folder I've discussed with @randomorder and PA already sent us some information.
/srv/ftp
I've update the readme file of the project according to the path of this folder.

**Comment by lpasquali** [comment]
> what's the status on this @lpasquali?
"1 day in total (including yesterday and this morning work"
we are close to finish here, I just need to add some configurations and make possible for dbait system user to read the data in /srv//ftp

**Comment by randomorder** [comment]
let's close this ASAP

**Comment by lpasquali** [comment]
> let's close this ASAP

@chpicone @randomorder 
quick follow up:

- app is working on the test vm and I'm finishing documenting everything
- still need to get ldap information
- PA still needs to do the addition of ip addres to configure vhost

**Comment by lpasquali** [comment]
follow up:

- @chpicone had to change the kind of sql queries for import/export in dramatiq/qgis distributed in deb packages does not come with postgres provider (at least for python)
- still need information about webserver and ldap from PA

**Comment by chpicone** [comment]
@lpasquali:
1) I am not sure about this point (what do you mean with knid of sql queries?)
2) They will provide us information about VHOST and LDAP structure. To access LDAP we can use the same configuration used with the WebGIS project.

**Comment by randomorder** [comment]
PA got back to us with the "contesti di bilanciamento" and LDAP config

**Comment by lpasquali** [comment]
@chpicone added configuration for ldap
as soon as they fix firewall ports for the webserver <---> django application connection we can schedule a reload of apache with PA, I will mail DeVitis for that
I already prepared configuration for webserver 
let me know if this could be ok:
- browse https://dbi.publiacqua.it for production so we leave the root for the future production application
- browse https://dbi.publiacqua.it/qas for qas/test for the current app under test.
if these are ok I will start updating also our manual with all the virtual hosts / credentials for web services

**Comment by chpicone** [comment]
It is ok for me. 
Both (Test/Prod) application will use the same LDAP.

**Comment by lpasquali** [comment]
> It is ok for me.
> Both (Test/Prod) application will use the same LDAP.

@chpicone  concerning ldap I see that the ldap module is commented in settings.py
also this dictionary:
```python
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    'is_staff': "cn=managements,{}".format(AUTH_LDAP_GROUP_BASE),
    'is_superuser': "cn=administrators,{}".format(AUTH_LDAP_GROUP_BASE),
}
```
shoud be transformed like or in any similar way is more preferrable:
```python
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    'is_operator': "cn=dbiaitoperator,{}".format(AUTH_LDAP_GROUP_BASE),
    'is_staff': "cn=dbiaitmanagement,{}".format(AUTH_LDAP_GROUP_BASE),
    'is_superuser': "cn=dbiaitadministrator,{}".format(AUTH_LDAP_GROUP_BASE),
}
```

**Comment by lpasquali** [comment]
I tested ldap from command line and it is working from the machine and I see all needed groups
I prepared the http virtualhost and I'm waiting for green light to do my restarts to services

**Comment by chpicone** [comment]
@lpasquali do you have ldap users to test? Can you add this information on the document on GDrive?

**Comment by lpasquali** [comment]
@chpicone 
https://docs.google.com/document/d/1ieocK40MCw74aIpB6HusdtNi9vLIi91egFs_b_yXRcc/edit#heading=h.avjn5rw9cvj

**Comment by lpasquali** [comment]
@chpicone can we put this in blocked until https://github.com/geosolutions-it/C179-DBIAIT/issues/131 is done? I also still need to hear from PA about the fact we can't reach the vhosts from vpn, at least I can't

**Comment by lpasquali** [comment]
@chpicone starting tests with ldap

**Comment by lpasquali** [comment]
@randomorder  @chpicone unfortunately for some yet unknwon reasons both ldap and url path handling are not working, we did some debug with @mattiagiupponi and recorded some information on the dedicated issue

**Comment by lpasquali** [comment]
@chpicone environment you gave me applied. noi doing "Aggiorna Codice" job you will issue code pull from master for now, let me know if you need the job to do more, I kept it doing the essential

**Comment by lpasquali** [comment]
@chpicone I think we can finally close this, ldap, apache, worked out correctly
