### ISSUE TITLE
Test QGIS installation on Ubuntu Server 18.04.03 LTS

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#77]
As discussed with the customer they prefer to dont use docker if it is possible.
So the proposed us to have a VM with Ubuntu Server 18.04.04 LTS.
Before to ask them to create a VM in their Test environment (and then in the PROD environment) we need to test QGIS installation headless.
Just to remember currently we are using:
QGIS 3.12.2 

- Bucaresti
- Python 3.8.x

We have to execute the same script used in the previous configuration (and in docker)

**Comment by lpasquali** [comment]
@randomorder @giacomoc92 if I remember correctly from yesterday the ubuntu machine should be ready, is this correct?

**Comment by randomorder** [comment]
Yes. I mentioned you in the issue

**Comment by lpasquali** [comment]
@chpicone at the moment Ubuntu and qgis only support current stable 3.16 and LTS 3.10 not 3.12
python version in ubuntu, and the one of the qgis python module is compiled with is 3.6.9
With qgis 3.16 I get:
```
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os,sys
>>> os.environ["QT_QPA_PLATFORM"] = "offscreen"
>>> from qgis.core import *
>>> from qgis.analysis import QgsNativeAlgorithms
>>> qgis_path = "/usr/share/qgis"
>>> QgsApplication.setPrefixPath(qgis_path, True)
>>> qgs = QgsApplication([], True)
>>> qgs.initQgis()
>>> sys.path.append(qgis_path + r'/python/plugins')
>>> from processing.core.Processing import Processing
>>> from processing.tools import postgis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'postgis'
>>> Processing.initialize()
>>> QgsApplication.processingRegistry().addProvider(QgsNativeAlgorithms())
True
>>> 
```

with 3.10 I get:
```
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os,sys
>>> os.environ["QT_QPA_PLATFORM"] = "offscreen"
>>> from qgis.core import *
>>> from qgis.analysis import QgsNativeAlgorithms
>>> qgis_path = "/usr/share/qgis"
>>> QgsApplication.setPrefixPath(qgis_path, True)
>>> qgs = QgsApplication([], True)
>>> qgs.initQgis()
>>> sys.path.append(qgis_path + r'/python/plugins/')
>>> import processing
>>> from processing.core.Processing import Processing
>>> from processing.tools import postgis
>>> Processing.initialize()
>>> QgsApplication.processingRegistry().addProvider(QgsNativeAlgorithms())
True
>>> 
```

**Comment by lpasquali** [comment]
@chpicone could the LTS 3.10.x be worth a try since the flawless test above (it has the old postgis module like 3.12.x)?

**Comment by lpasquali** [comment]
```
geosolutions@qgis:~$ python3 
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os,sys
>>> os.environ["QT_QPA_PLATFORM"] = "offscreen"
>>> from qgis.core import *
>>> from qgis.analysis import QgsNativeAlgorithms
>>> qgis_path = "/usr/share/qgis"
>>> QgsApplication.setPrefixPath(qgis_path, True)
>>> qgs = QgsApplication([], True)
>>> qgs.initQgis()
>>> sys.path.append(qgis_path + r'/python/plugins/')
>>> import processing
>>> from processing.core.Processing import Processing
>>> from processing.tools import postgis
>>> Processing.initialize()
>>> QgsApplication.processingRegistry().addProvider(QgsNativeAlgorithms())
True
>>>
```

machine is ready for testing

**Comment by chpicone** [comment]
@lpasquali I will test it tomorrow.
I think maybe not more necessary to have the "postgis" module, because we found an alternative (in this case we can use QGIS 3.16).
But to be sure better to make a test.

**Comment by lpasquali** [comment]
@chpicone 3.16 is ready on server, I spoke with @randomorder and I am going to add necessary software (nginx, rabbit, postgres, and so on..) to the complete test

**Comment by lpasquali** [comment]
Test was a success for qgis 3.16 + python 3.6

**Comment by randomorder** [comment]
Anything else to do here @lpasquali ?

**Comment by lpasquali** [comment]
@randomorder I should document the final procedure and maybe the whole installation procedure as we spoke today

**Comment by lpasquali** [comment]
Embrional documentation for production and test installations [here](https://docs.google.com/document/d/1KJOHqDIgIzY0AFfy6W87VmHmd-mr8lQmhzmVf1GeHl8/edit#). This should be updated as soon as it is decided how to run the process for scheduling tasks, using python dramatiq

This installs QGIS 3.16.x


@chpicone @randomorder

**Comment by randomorder** [comment]
thanks
