### ISSUE TITLE
Import Page > "Storico": show log to the status icon

### ISSUE THREAD

**Issue by chpicone** [geosolutions-it/C179-DBIAIT#95]
When the user click on the icon for the status of a task show the associated log (the same as in the process page):

![image.png](https://images.zenhubusercontent.com/5e98219c18069195a59f5217/6c237fd0-0742-418b-bb96-66fc66c1b117)

**Comment by mattiagiupponi** [comment]
As decided with Christian, we will integrate also datatables in order to have a better visualization of the table
